"""empty message

Revision ID: 0d2a80d87a89
Revises: 9e2c15ecb0a0
Create Date: 2021-04-10 21:36:59.465753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2a80d87a89'
down_revision = '9e2c15ecb0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('estado_civil', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'estado_civil')
    # ### end Alembic commands ###
