"""empty message

Revision ID: 0d4f0b81210e
Revises: f61e788a012a
Create Date: 2021-04-11 10:25:08.971528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4f0b81210e'
down_revision = 'f61e788a012a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=True),
    sa.Column('tipo_usuario_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_usuario_id'], ['tipos_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pessoas', sa.Column('nm_mae', sa.String(length=100), nullable=True))
    op.add_column('pessoas', sa.Column('nm_pai', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'nm_pai')
    op.drop_column('pessoas', 'nm_mae')
    op.drop_table('usuarios')
    op.drop_table('tipos_usuarios')
    # ### end Alembic commands ###
