"""empty message

Revision ID: 2a71b9f48d9c
Revises: 0d4f0b81210e
Create Date: 2021-04-11 10:45:35.832985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a71b9f48d9c'
down_revision = '0d4f0b81210e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_despesas_rendimentos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesas_rendimentos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('tipo_despesa_rendimento_id', sa.BigInteger(), nullable=True),
    sa.Column('funcionario_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_despesa_rendimento_id'], ['tipos_despesas_rendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas_rendimentos')
    op.drop_table('tipos_despesas_rendimentos')
    # ### end Alembic commands ###
