"""empty message

Revision ID: 52538dc15416
Revises: 0d2a80d87a89
Create Date: 2021-04-10 21:52:16.557244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52538dc15416'
down_revision = '0d2a80d87a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('bairro', sa.String(length=50), nullable=True))
    op.add_column('pessoas', sa.Column('celular1', sa.String(length=10), nullable=True))
    op.add_column('pessoas', sa.Column('celular2', sa.String(length=10), nullable=True))
    op.add_column('pessoas', sa.Column('celular3', sa.String(length=10), nullable=True))
    op.add_column('pessoas', sa.Column('celular4', sa.String(length=10), nullable=True))
    op.add_column('pessoas', sa.Column('cep', sa.String(length=10), nullable=True))
    op.add_column('pessoas', sa.Column('cidade', sa.String(length=50), nullable=True))
    op.add_column('pessoas', sa.Column('complemento', sa.String(length=50), nullable=True))
    op.add_column('pessoas', sa.Column('ddd', sa.String(length=2), nullable=True))
    op.add_column('pessoas', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('pessoas', sa.Column('logradouro', sa.String(length=100), nullable=True))
    op.add_column('pessoas', sa.Column('nu_logradouro', sa.String(length=5), nullable=True))
    op.add_column('pessoas', sa.Column('telefone1', sa.String(length=10), nullable=True))
    op.add_column('pessoas', sa.Column('telefone2', sa.String(length=10), nullable=True))
    op.add_column('pessoas', sa.Column('uf', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'uf')
    op.drop_column('pessoas', 'telefone2')
    op.drop_column('pessoas', 'telefone1')
    op.drop_column('pessoas', 'nu_logradouro')
    op.drop_column('pessoas', 'logradouro')
    op.drop_column('pessoas', 'email')
    op.drop_column('pessoas', 'ddd')
    op.drop_column('pessoas', 'complemento')
    op.drop_column('pessoas', 'cidade')
    op.drop_column('pessoas', 'cep')
    op.drop_column('pessoas', 'celular4')
    op.drop_column('pessoas', 'celular3')
    op.drop_column('pessoas', 'celular2')
    op.drop_column('pessoas', 'celular1')
    op.drop_column('pessoas', 'bairro')
    # ### end Alembic commands ###
