"""empty message

Revision ID: 54db3a51b0ba
Revises: 8362ae38426a
Create Date: 2021-04-11 11:25:27.735695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54db3a51b0ba'
down_revision = '8362ae38426a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('secao', sa.String(length=20), nullable=True))
    op.add_column('funcionarios', sa.Column('titulo', sa.String(length=20), nullable=True))
    op.add_column('funcionarios', sa.Column('zona', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'zona')
    op.drop_column('funcionarios', 'titulo')
    op.drop_column('funcionarios', 'secao')
    # ### end Alembic commands ###
