"""empty message

Revision ID: 5cbfa29269d7
Revises: adaa478e2543
Create Date: 2021-04-10 23:10:26.846646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbfa29269d7'
down_revision = 'adaa478e2543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contatos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ddd', sa.String(length=2), nullable=True),
    sa.Column('telefone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('pessoas', 'celular2')
    op.drop_column('pessoas', 'celular3')
    op.drop_column('pessoas', 'celular4')
    op.drop_column('pessoas', 'email')
    op.drop_column('pessoas', 'telefone2')
    op.drop_column('pessoas', 'celular1')
    op.drop_column('pessoas', 'telefone1')
    op.drop_column('pessoas', 'ddd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('ddd', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('telefone1', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('celular1', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('telefone2', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('celular4', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('celular3', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('celular2', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_table('contatos')
    # ### end Alembic commands ###
