"""empty message

Revision ID: 8362ae38426a
Revises: 868d5f299ac6
Create Date: 2021-04-11 11:23:02.223827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8362ae38426a'
down_revision = '868d5f299ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('funcionarios_caixa_id_fkey', 'funcionarios', type_='foreignkey')
    op.drop_column('funcionarios', 'caixa_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('caixa_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('funcionarios_caixa_id_fkey', 'funcionarios', 'caixas', ['caixa_id'], ['id'])
    # ### end Alembic commands ###
