"""empty message

Revision ID: 868d5f299ac6
Revises: 2a71b9f48d9c
Create Date: 2021-04-11 11:21:21.236099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868d5f299ac6'
down_revision = '2a71b9f48d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dt_rendimento', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('funcionarios', sa.Column('caixa_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'funcionarios', 'caixas', ['caixa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funcionarios', type_='foreignkey')
    op.drop_column('funcionarios', 'caixa_id')
    op.drop_table('caixas')
    # ### end Alembic commands ###
