"""empty message

Revision ID: adaa478e2543
Revises: 52538dc15416
Create Date: 2021-04-10 22:56:01.831428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adaa478e2543'
down_revision = '52538dc15416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('matricula', sa.String(length=10), nullable=False),
    sa.Column('dt_admissao', sa.Date(), nullable=False),
    sa.Column('dt_desligamento', sa.Date(), nullable=True),
    sa.Column('ctps', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionarios')
    # ### end Alembic commands ###
