"""empty message

Revision ID: b9d1340d092a
Revises: dcf032dea805
Create Date: 2021-04-21 15:03:16.744599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d1340d092a'
down_revision = 'dcf032dea805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos_caixa',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade_produto_comprado', sa.Integer(), nullable=False),
    sa.Column('total_compra', sa.Float(precision=16, asdecimal=2), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=True),
    sa.Column('caixa_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos_caixa')
    # ### end Alembic commands ###
