"""empty message

Revision ID: dcf032dea805
Revises: 
Create Date: 2021-04-21 14:38:35.112677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf032dea805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('dt_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('nm_mae', sa.String(length=100), nullable=True),
    sa.Column('nm_pai', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('produtos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo_barra', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(precision=16, asdecimal=2), nullable=False),
    sa.Column('preco_venda', sa.Float(precision=16, asdecimal=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barra')
    )
    op.create_table('tipos_despesas_rendimentos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contatos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ddd', sa.String(length=2), nullable=True),
    sa.Column('telefone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('logradouro', sa.String(length=100), nullable=True),
    sa.Column('nu_logradouro', sa.String(length=5), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('matricula', sa.String(length=10), nullable=False),
    sa.Column('dt_admissao', sa.Date(), nullable=False),
    sa.Column('dt_desligamento', sa.Date(), nullable=True),
    sa.Column('ctps', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=20), nullable=True),
    sa.Column('titulo', sa.String(length=20), nullable=True),
    sa.Column('zona', sa.String(length=20), nullable=True),
    sa.Column('secao', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('caixas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dt_rendimento', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesas_rendimentos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('tipo_despesa_rendimento_id', sa.BigInteger(), nullable=True),
    sa.Column('funcionario_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_despesa_rendimento_id'], ['tipos_despesas_rendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=True),
    sa.Column('tipo_usuario_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_usuario_id'], ['tipos_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('despesas_rendimentos')
    op.drop_table('caixas')
    op.drop_table('funcionarios')
    op.drop_table('enderecos')
    op.drop_table('contatos')
    op.drop_table('tipos_usuarios')
    op.drop_table('tipos_despesas_rendimentos')
    op.drop_table('produtos')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
