"""empty message

Revision ID: f61e788a012a
Revises: 5cbfa29269d7
Create Date: 2021-04-11 10:04:13.225035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61e788a012a'
down_revision = '5cbfa29269d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('logradouro', sa.String(length=100), nullable=True),
    sa.Column('nu_logradouro', sa.String(length=5), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('pessoa_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('pessoas', 'nu_logradouro')
    op.drop_column('pessoas', 'complemento')
    op.drop_column('pessoas', 'cep')
    op.drop_column('pessoas', 'uf')
    op.drop_column('pessoas', 'cidade')
    op.drop_column('pessoas', 'logradouro')
    op.drop_column('pessoas', 'bairro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('bairro', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('logradouro', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('cidade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('uf', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('cep', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('complemento', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('pessoas', sa.Column('nu_logradouro', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_table('enderecos')
    # ### end Alembic commands ###
